### ISSUE TITLE
Error and overloaded 

### ISSUE THREAD

**Issue by headhunter12744** [PaladinSRV/issues#13]
![Screenshot_20240610_022003_Chrome](https://github.com/PaladinSRV/issues/assets/172081578/63473b1a-67f6-4af0-84c3-5260b0ec4ab1)

Everytime I'm opening my server this message pops up after everything is up and running and after a while the server automatically shuts down.
Discord srv bot says that the server hasn't been ticked for some seconds. Are the nodes overloaded? Is it a bug or something? (Using the pro node nl.ams)

**Comment by headhunter12744** [comment]
[latest.log](https://github.com/user-attachments/files/15755048/latest.log)

And if I'm not wrong this is the log file with the full issue

**Comment by KingTino104** [comment]
We will be implementing resource limits soon.
