### ISSUE TITLE
There is too little space allocated for Qemu Images of Linux 

### ISSUE THREAD

**Issue by Zyjkjuejej** [PaladinSRV/issues#21]
Hello, I am facing a problem that the debian system image is only allocated 1G, this is not enough, please change the debian/other system image to 80 Gigabytes. 
![image](https://github.com/PaladinSRV/issues/assets/99591594/c7209fde-7352-4535-8754-042a803e3154)
![image](https://github.com/PaladinSRV/issues/assets/99591594/8b3f6c71-86b4-41f2-8706-9aa875241175)

**Comment by KingTino104** [comment]
https://lumenvm.cloud/docs/?page=Documentation/images
