### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by CubeBeveled** [PaladinSRV/issues#23]
* Make it so we can react in announcements
* Make the QEMU image size bigger by default (also yes i saw another issue talking about this)
* Add more OSes to the list
* Update the [status page](https://status.paladinsrv.com/) (some nodes are missing) and keep updating it
* Disk space in nodes is still pretty high so please keep working on that
* Add statbot to the discord server for cool stats
* Make it so the discord bot you authorize on login stays authorized so we stay logged in
* Fix swap
* Many new users haven't seen the announcement where it was stated where suggestions were moved so they dont know that u have a place for suggestions + many ppl might not have a github account.
**You can solve this by** moving suggestions back to the discord server _OR_ making a channel in said server where theres an explanation and link to this place

**Comment by KingTino104** [comment]
![image](https://github.com/PaladinSRV/issues/assets/90916297/96bd5d8b-c6f5-4e86-bee6-f29e51556f8e)
i dont see anything missing (ignore vie and swe)

oses in server creation wont be added but you can change the docker image we have alpine, arch & debian 12

reactions will be enabled if we have less indians thinking their country is the best on earth

qemu image size might be changed  but i dont have a server to host it so

yup, we are working on the disk space stuff

statbot, no

there are sessions but they dont work that good + i recently added it so it auto redirects u to /dashboard if u are logged in

i cant fix swap 

#information channel it does say "Issues/suggestions: https://github.com/paladinsrv/issues"
