### ISSUE TITLE
Deleted servers without resources back

### ISSUE THREAD

**Issue by yassinx5** [PaladinSRV/issues#4]
i had servers but they somehow got deleted and i never got my resources back like fine delete the server give me my recourses to use them again
![Screenshot_20240607-225438_Chrome](https://github.com/PaladinSRV/issues/assets/83985180/c1a008d3-190c-4acb-bad8-186bf4892e4f)
![Screenshot_20240607-225429_Chrome](https://github.com/PaladinSRV/issues/assets/83985180/9617c505-cbde-48c9-8cef-fe21194fafd0)

**Comment by KingTino104** [comment]
u got ur resources back, all of your resources are available

**Comment by yassinx5** [comment]
> u got ur resources back, all of your resources are available

no i didnt
![Screenshot_20240607-230725_Chrome](https://github.com/PaladinSRV/issues/assets/83985180/32a102f2-83e4-4eb4-80c9-559852d1db19)

this is my email yassinayman999@yahoo.com check for yourself

**Comment by KingTino104** [comment]
cant you see your resources are "usage: 0"

**Comment by yassinx5** [comment]
> cant you see your resources are "usage: 0"

oh xd sorry
