### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by headhunter12744** [PaladinSRV/issues#5]
3 days ago the server was starting but VERY slowly and after it opened the console start spamming errors and that this wasn't a purpur bug or issue.
Now 3 days after that my server opens until the part where it says something about container and then is automatically shuts down. Also the version management is startup isn't working I try putting my version for example 1.20.1 but after refreshing or going to other page (for example settings) it resets (USING PRO)

**Comment by KingTino104** [comment]
server link

**Comment by headhunter12744** [comment]
> server link

Here you are https://panel.paladinsrv.com/server/9fee03b1

**Comment by KingTino104** [comment]
There are no issues

**Comment by headhunter12744** [comment]
> There are no issues

What do you mean? In the startup page when I add the mc version and refresh the page it goes back to latest. And the server doesn't open. And it isn't only mine but a friend of mine too has the same problem (without the server not opening). Is it maybe a bug in my side? I can share screen you if you want
